### ISSUE TITLE
Convert Yelp $$$ notation to price ranges

### ISSUE THREAD

**Issue by fechan** [conzensus/conzensus#37]
The Activity price range is still just [0,9999] since I didn't know what the $ actually denote.

**Comment by makenzieedwards8** [comment]
Not sure this will work since, especially with restaurants, there is a huge range of what you may spend with the different dollar amounts of items on the menu. The $$$ are used as a generalized average of what one can expect, but do not represent a specific dollar range.

**Comment by fechan** [comment]
I don't think we could get a precise measure of what the $$$ means for each restaurant, but I feel like it would still be useful to report what the expected range is:

```
Yelp use dollar signs ($) to categorize approximate cost per person for a meal in a restaurant. In particular, “$” means under $10; “$ $” means “$11-$30”; “$ $ $” means “$31-$60”; and “$ $ $ $” means “above $61”. Accordingly, we measured price levels from 1 to 4, and higher level means more expensive.
```
Source: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0252157

Personally I'm always a little confused whether $$ is within my price range when I'm using Yelp, and I'd find a more concrete range would help.

We *could* calculate a more precise range by getting the restaurants menu and calculating the price range for items on the menu... this sounds a little involved but it is possible.

**Comment by fechan** [comment]
Currently just returning "$$$" etc. to the client
